# SPDX-License-Identifier: MIT
"""Behavioral tests for the release-artifact inventory gate (#251)."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from check_release_inventory import (  # noqa: E402
    main,
    manifest,
    release_files,
    scan,
)
import check_release_inventory as cri  # noqa: E402


def test_real_release_set_is_clean():
    """The actual repo HEAD release set must carry no forbidden paths/references."""
    assert main([]) == 0


def test_forbidden_paths_are_flagged():
    files = [
        "adapter/core/sensitive.py",
        ".bicameral/factory-attestations/abc.json",
        ".github/workflows/ci.yml",
        "docs/governance/BOUNDARY.md",
        "docs/SHADOW_GENOME.md",
    ]
    problems = scan(files)
    joined = "\n".join(problems)
    assert ".bicameral/factory-attestations/abc.json" in joined
    assert ".github/workflows/ci.yml" in joined
    assert "docs/governance/BOUNDARY.md" in joined
    assert "docs/SHADOW_GENOME.md" in joined
    # A legitimate product path is never flagged.
    assert "adapter/core/sensitive.py" not in joined


def test_forbidden_references_are_flagged(tmp_path, monkeypatch):
    monkeypatch.setattr(cri, "ROOT", tmp_path)
    leak = tmp_path / "docs" / "leak.md"
    leak.parent.mkdir(parents=True)
    leak.write_text(
        "See https://github.com/BicameralAI/bicameral-factory and the .qor/ scratch, "
        "generated by Qor-logic; bic-logic is stale. FailSafe / MythologIQ. Shadow Genome.",
        encoding="utf-8",
    )
    problems = cri._scan_references("docs/leak.md")
    labels = "\n".join(problems)
    assert "private Factory repository link" in labels
    assert "stale bic-logic terminology" in labels
    assert "Qor-logic" in labels
    assert "FailSafe" in labels
    assert "internal sibling-tool path (.qor/)" in labels
    assert "Shadow Genome" in labels


def test_product_connector_names_are_not_treated_as_internal_tools(
    tmp_path, monkeypatch
):
    """A product doc that ingests Cursor/Claude Code data is legitimate, not a leak."""
    monkeypatch.setattr(cri, "ROOT", tmp_path)
    doc = tmp_path / "connectors" / "cursor" / "README.md"
    doc.parent.mkdir(parents=True)
    doc.write_text(
        "The Cursor connector ingests Cursor and Claude Code evidence.",
        encoding="utf-8",
    )
    assert cri._scan_references("connectors/cursor/README.md") == []


def test_manifest_is_deterministic():
    files = release_files()
    first = manifest(files)
    second = manifest(files)
    assert first == second
    assert "sha256:" in first
    assert f"{len(files)} files" in first
