name: OpenSSF Scorecard

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "15 7 * * 1"

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    uses: ./.github/workflows/_reusable-scorecard.yml
